### ISSUE TITLE
Coverage Evaluation

### ISSUE THREAD

**Issue by maxammann** [tlspuffin/tlspuffin#242]
## Targets:
* OpenSSL 1.1.1 (one version e.g. f/k)
* wolfSSL 5.3.0

## Fuzzers/Testers:
* AFLNet/StateAFL/AFLNew (through [profuzzbench](https://github.com/profuzzbench/profuzzbench/tree/master/subjects/TLS/OpenSSL))
* TLSAnvil

## Methodology:

**Option A)**

* Let the fuzzer run for 1h or 24h and collect corpus
* Instrument a plain statically compiled server executable with coverage
* Execute the corpus over TCP against the server (In AFLNet this is done through afl-replay https://github.com/aflnet/aflnet/blob/master/afl-replay.c)

Issues:
* ⚠️ In tlspuffin we use a custom setup of the server (certificate, options)

**Option B)**

* Use Option A) for AFLNet, TLSAnvil
  * ...
* Let the fuzzer run for 1h or 24h and collect corpus
* Compile a libssl.a static library just like the coverage binary from Option A)
  * Do not use any fuzzing specific flags for this binary! No -fsanitze=coverage! Use `-fprofile-arcs -ftest-coverage`!
  * Requires a build of tlspuffin which is designed for coverage evaluation.
* Use libssl.a in tlspuffin and execute the seed corpus

## TODO

* [x] Adjust coverage filters for profuzzbench
* [x] Compile without optimizations
* [x] #244
* [x] **Enable 1.2 and 1.3** (wolfssl: -v d -7 3)
* profuzzbench
  * [x] Create a coverage.csv from profuzzbench with OpenSSL
    * [x] StateAFL
    * [x] AFLNwe
    * [x] AFLNet
  * [x] Create a coverage.csv from profuzzbench with wolfSSL
    * [x] StateAFL
    * [x] AFLNwe
    * [x] AFLNet

* tlspuffin
  * [x] Create a coverage.csv from tlspuffin with OpenSSL
  * [x] Create a coverage.csv from tlspuffin with wolfSSL

* TLSAnvil
  * [x] Generate max. coverage from TLS-Anvil with OpenSSL
    Coverage with TLS-Anvil when testing an OpenSSL 1.1.1j server:

  * [x] Generate max. coverage from TLS-Anvil with wolfSSL
* ~Precompiled~ (Instead of precompiled I validated that the max. line count matches across all campaign evaluations)
  * [x] Use precompiled OpenSSL with TLS-Anvil with OpenSSL
  * [x] Use precompiled OpenSSL with profuzzbench
  * [x] Use precompiled OpenSSL with TLS-Anvil with wolfSSL
  * [x] Use precompiled wolfSSL with profuzzbench
  * [x] Use precompiled OpenssL with tlspuffin
  * [x] Use precompiled wolfSSL with tlspuffin

**Comment by maxammann** [comment]
Related:
* https://github.com/tls-attacker/TLS-Anvil/issues/11
* https://github.com/stateafl/stateafl/issues/10

StateAFL -K bug:
* https://github.com/stateafl/stateafl/blob/d923e22f7b2688db45b08f3fa3a29a566e7ff3a4/llvm_mode/afl-llvm-rt-state-tracer.o.c#L1879
* https://github.com/stateafl/stateafl/blob/d923e22f7b2688db45b08f3fa3a29a566e7ff3a4/README-AFLnet.md?plain=1#L248

**Comment by maxammann** [comment]
AFLnwe: -f .tmp-file to workaround short read

**Comment by maxammann** [comment]
Execution plan:

* Profuzzbench fuzzers (aflnet, aflnwe, stateafl): 10 trials, 24h each
  * Fuzzes wolfSSL and OpenSSL TLS 1.3 servers
  * 10 (trials) * 2 (targets) * 3 (fuzzers) = 60 campaigns
  * -> Coverage plot
* tlspuffin: 10 trials, 24h, each one core
  * Restrict to TLS 1.3 servers  
  * 10 (trials) * 2 (targets) = 20 campaigns
  * -> Coverage plot
* tlspuffin 32 cores, 24h, 1 trial
  * 1 (trials) * 2 (targets) = 2 campaigns
  * -> Single coverage number
* TLS Anvil
  * Test first clients and then servers
  * 1 (trials) * 2 (targets) = 2 campaigns
  * -> Single coverage number

The final result of this evaluation will be:
* a large coverage plot, which includes tlspuffin, StateAFL, AFLNet and AFLnwe
* Single number coverage comparision between TLS Anvil and tlspuffin and something like tlspuffin reached 95% the coverage of TLS Anvil after x hours.

**Comment by maxammann** [comment]
## Pain points during evaluation

* Getting StateAFL running (-K flag)
* Getting AFLnwe runnign (-f flag)
* tlspuffin uses Cargo for linking. This makes tlspuffin reproducible, but it is very hard to compare with others, because linking is done by rustc instead of having control
* Environment differences: like clang/gcc versions, gcov versions etc.

**Comment by maxammann** [comment]
* CVE-2022-38152 (SDOS2): Not reachable because wolfSSL_clear is not called
* CVE-2022-38153 (CDOS): Not reachable because not client is fuzzed
* CVE-2022-39173 (BUF): Not reachable because too hard.
* CVE-2022-42905 (HEADP): ??

**Comment by maxammann** [comment]
Running s_server with --rand-state=0 does not work -> crash

**Comment by maxammann** [comment]
* 9. - 10. May: Task A, A1, D (server)
* 10. - 11. May: Task B, C

**Comment by maxammann** [comment]
GCC and Clang calculate coverage differently, some seeses `case XYZ` as a line, the other doesn't.

**Comment by maxammann** [comment]
TODO: TLS-Anvil client versions? wolfssl client 1.2/1.3, openssl client 1.2/1.3

**Comment by maxammann** [comment]
Renegotiatoin Info in 5.3.0 is incompatible with TLS-Anvil: https://github.com/tls-attacker/TLS-Attacker/issues/152

**Comment by maxammann** [comment]
https://github.com/profuzzbench/profuzzbench/issues/6

**Comment by maxammann** [comment]
Fixed coverage misses when generating it. flush on exit

**Comment by maxammann** [comment]
Observed issues during this evaluation:

* AFLnwe: https://github.com/thuanpv/aflnwe/issues/2
* AFLnwe: https://github.com/thuanpv/aflnwe/issues/1
* AFLnwe: https://github.com/thuanpv/aflnwe/issues/3
* AFLnwe: https://github.com/thuanpv/aflnwe/issues/4
* TLS-Anvil: https://github.com/tls-attacker/TLS-Attacker/issues/152
* StateAFL: https://github.com/stateafl/stateafl/issues/11
